### ISSUE TITLE
Support mathml 

### ISSUE THREAD

**Issue by wzhsunn** [readium/SDKLauncher-Windows#27]
As you say: https://github.com/readium/readium-js-viewer/issues/323#issuecomment-95478578 , I read the code, but I think it is difficult for me to add mathml support.

Would you have a plan to do that ?
Thank you !
:)

**Comment by danielweck** [comment]
Duplicated issue: https://github.com/readium/SDKLauncher-Windows/issues/8


@wzhsunn as far as I know there are no immediate plans to implement MathML support in the basic Windows MFC application launcher that exists in a feature branch right now, due to lack of developer contributions in this area (at the moment).
